### ISSUE TITLE
error: Could not find suitable distribution for Requirement.parse('importlib')

### ISSUE THREAD

**Issue by Code4SAFrankie** [peter17/pijnu#12]
python setup.py install
running install
running bdist_egg
running egg_info
creating pijnu.egg-info
writing pijnu.egg-info\PKG-INFO
writing dependency_links to pijnu.egg-info\dependency_links.txt
writing requirements to pijnu.egg-info\requires.txt
writing top-level names to pijnu.egg-info\top_level.txt
writing manifest file 'pijnu.egg-info\SOURCES.txt'
reading manifest file 'pijnu.egg-info\SOURCES.txt'
writing manifest file 'pijnu.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_py
creating build
creating build\lib
creating build\lib\pijnu
copying pijnu\__init__.py -> build\lib\pijnu
creating build\lib\pijnu\generator
copying pijnu\generator\generator.py -> build\lib\pijnu\generator
copying pijnu\generator\genTest.py -> build\lib\pijnu\generator
copying pijnu\generator\genTestParser.py -> build\lib\pijnu\generator
copying pijnu\generator\None.py -> build\lib\pijnu\generator
copying pijnu\generator\pijnuActions.py -> build\lib\pijnu\generator
copying pijnu\generator\pijnuParser.py -> build\lib\pijnu\generator
copying pijnu\generator\__init__.py -> build\lib\pijnu\generator
creating build\lib\pijnu\library
copying pijnu\library\charset.py -> build\lib\pijnu\library
copying pijnu\library\error.py -> build\lib\pijnu\library
copying pijnu\library\gParser.py -> build\lib\pijnu\library
copying pijnu\library\node.py -> build\lib\pijnu\library
copying pijnu\library\parser.py -> build\lib\pijnu\library
copying pijnu\library\pattern.py -> build\lib\pijnu\library
copying pijnu\library\preprocess.py -> build\lib\pijnu\library
copying pijnu\library\testError.py -> build\lib\pijnu\library
copying pijnu\library\testing.py -> build\lib\pijnu\library
copying pijnu\library\testParserParser.py -> build\lib\pijnu\library
copying pijnu\library\testPattern.py -> build\lib\pijnu\library
copying pijnu\library\testValidParser.py -> build\lib\pijnu\library
copying pijnu\library\tools.py -> build\lib\pijnu\library
copying pijnu\library\__init__.py -> build\lib\pijnu\library
creating build\bdist.win-amd64
creating build\bdist.win-amd64\egg
creating build\bdist.win-amd64\egg\pijnu
creating build\bdist.win-amd64\egg\pijnu\generator
copying build\lib\pijnu\generator\generator.py -> build\bdist.win-amd64\egg\pijnu\generator
copying build\lib\pijnu\generator\genTest.py -> build\bdist.win-amd64\egg\pijnu\generator
copying build\lib\pijnu\generator\genTestParser.py -> build\bdist.win-amd64\egg\pijnu\generator
copying build\lib\pijnu\generator\None.py -> build\bdist.win-amd64\egg\pijnu\generator
copying build\lib\pijnu\generator\pijnuActions.py -> build\bdist.win-amd64\egg\pijnu\generator
copying build\lib\pijnu\generator\pijnuParser.py -> build\bdist.win-amd64\egg\pijnu\generator
copying build\lib\pijnu\generator\__init__.py -> build\bdist.win-amd64\egg\pijnu\generator
creating build\bdist.win-amd64\egg\pijnu\library
copying build\lib\pijnu\library\charset.py -> build\bdist.win-amd64\egg\pijnu\library
copying build\lib\pijnu\library\error.py -> build\bdist.win-amd64\egg\pijnu\library
copying build\lib\pijnu\library\gParser.py -> build\bdist.win-amd64\egg\pijnu\library
copying build\lib\pijnu\library\node.py -> build\bdist.win-amd64\egg\pijnu\library
copying build\lib\pijnu\library\parser.py -> build\bdist.win-amd64\egg\pijnu\library
copying build\lib\pijnu\library\pattern.py -> build\bdist.win-amd64\egg\pijnu\library
copying build\lib\pijnu\library\preprocess.py -> build\bdist.win-amd64\egg\pijnu\library
copying build\lib\pijnu\library\testError.py -> build\bdist.win-amd64\egg\pijnu\library
copying build\lib\pijnu\library\testing.py -> build\bdist.win-amd64\egg\pijnu\library
copying build\lib\pijnu\library\testParserParser.py -> build\bdist.win-amd64\egg\pijnu\library
copying build\lib\pijnu\library\testPattern.py -> build\bdist.win-amd64\egg\pijnu\library
copying build\lib\pijnu\library\testValidParser.py -> build\bdist.win-amd64\egg\pijnu\library
copying build\lib\pijnu\library\tools.py -> build\bdist.win-amd64\egg\pijnu\library
copying build\lib\pijnu\library\__init__.py -> build\bdist.win-amd64\egg\pijnu\library
copying build\lib\pijnu\__init__.py -> build\bdist.win-amd64\egg\pijnu
byte-compiling build\bdist.win-amd64\egg\pijnu\generator\generator.py to generator.cpython-36.pyc
byte-compiling build\bdist.win-amd64\egg\pijnu\generator\genTest.py to genTest.cpython-36.pyc
byte-compiling build\bdist.win-amd64\egg\pijnu\generator\genTestParser.py to genTestParser.cpython-36.pyc
byte-compiling build\bdist.win-amd64\egg\pijnu\generator\None.py to None.cpython-36.pyc
byte-compiling build\bdist.win-amd64\egg\pijnu\generator\pijnuActions.py to pijnuActions.cpython-36.pyc
byte-compiling build\bdist.win-amd64\egg\pijnu\generator\pijnuParser.py to pijnuParser.cpython-36.pyc
byte-compiling build\bdist.win-amd64\egg\pijnu\generator\__init__.py to __init__.cpython-36.pyc
byte-compiling build\bdist.win-amd64\egg\pijnu\library\charset.py to charset.cpython-36.pyc
byte-compiling build\bdist.win-amd64\egg\pijnu\library\error.py to error.cpython-36.pyc
byte-compiling build\bdist.win-amd64\egg\pijnu\library\gParser.py to gParser.cpython-36.pyc
byte-compiling build\bdist.win-amd64\egg\pijnu\library\node.py to node.cpython-36.pyc
byte-compiling build\bdist.win-amd64\egg\pijnu\library\parser.py to parser.cpython-36.pyc
byte-compiling build\bdist.win-amd64\egg\pijnu\library\pattern.py to pattern.cpython-36.pyc
byte-compiling build\bdist.win-amd64\egg\pijnu\library\preprocess.py to preprocess.cpython-36.pyc
byte-compiling build\bdist.win-amd64\egg\pijnu\library\testError.py to testError.cpython-36.pyc
byte-compiling build\bdist.win-amd64\egg\pijnu\library\testing.py to testing.cpython-36.pyc
byte-compiling build\bdist.win-amd64\egg\pijnu\library\testParserParser.py to testParserParser.cpython-36.pyc
byte-compiling build\bdist.win-amd64\egg\pijnu\library\testPattern.py to testPattern.cpython-36.pyc
byte-compiling build\bdist.win-amd64\egg\pijnu\library\testValidParser.py to testValidParser.cpython-36.pyc
byte-compiling build\bdist.win-amd64\egg\pijnu\library\tools.py to tools.cpython-36.pyc
byte-compiling build\bdist.win-amd64\egg\pijnu\library\__init__.py to __init__.cpython-36.pyc
byte-compiling build\bdist.win-amd64\egg\pijnu\__init__.py to __init__.cpython-36.pyc
creating build\bdist.win-amd64\egg\EGG-INFO
copying pijnu.egg-info\PKG-INFO -> build\bdist.win-amd64\egg\EGG-INFO
copying pijnu.egg-info\SOURCES.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying pijnu.egg-info\dependency_links.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying pijnu.egg-info\requires.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying pijnu.egg-info\top_level.txt -> build\bdist.win-amd64\egg\EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating dist
creating 'dist\pijnu-20160728-py3.6.egg' and adding 'build\bdist.win-amd64\egg' to it
removing 'build\bdist.win-amd64\egg' (and everything under it)
Processing pijnu-20160728-py3.6.egg
Copying pijnu-20160728-py3.6.egg to c:\programdata\anaconda3\lib\site-packages
Adding pijnu 20160728 to easy-install.pth file

Installed c:\programdata\anaconda3\lib\site-packages\pijnu-20160728-py3.6.egg
Processing dependencies for pijnu==20160728
Searching for importlib
Reading https://pypi.python.org/simple/importlib/
Download error on https://pypi.python.org/simple/importlib/: [Errno 11002] getaddrinfo failed -- Some packages may not be found!
Couldn't find index page for 'importlib' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading https://pypi.python.org/simple/
No local packages or working download links found for importlib
error: Could not find suitable distribution for Requirement.parse('importlib')

Python 3.6.1 |Anaconda 4.4.0 (64-bit)| (default, May 11 2017, 13:25:24) [MSC v.1900 64 bit (AMD64)] on win32

**Comment by peter17** [comment]
Hi,

` Download error on https://pypi.python.org/simple/importlib/: [Errno 11002] getaddrinfo failed -- Some packages may not be found!`

This does not seem to be a problem with Pijnu but rather with your system and/or Internet connection.

I am closing this issue.

Best regards
